[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tpac.x", # memory.x must appear BEFORE link.x
    "-C", "link-arg=-Tdevice.x", # memory.x must appear BEFORE link.x
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "riscv32i-unknown-none-elf"
